version: '3'

services:

  php-fpm:
    container_name: php-fpm
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www/public

  db:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - 3307:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_DATABASE: api_tennis

  maildev:
    image: djfarrelly/maildev
    ports:
    - "8002:80"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
    - "8080:80"
    depends_on:
    - db
    environment:
      PMA_HOST: db
